### PR TITLE
Test sfdp and triangulation library dependency

### PR DESCRIPTION
**Pull request by peterjc**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See #31

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Peter! 😄

Could we please add the same thing to `run_test.bat`?

**Comment by nehaljwani** [comment]
Whoops, need to enable gts for all linux-*! Will fix.

**Comment by jakirkham** [comment]
Thanks Nehal! 😄

Were we including this in the Windows build as well or was I mistaken in thinking that?

**Comment by nehaljwani** [comment]
I'm tackling gts support in this MR: https://github.com/conda-forge/graphviz-feedstock/pull/60
I've cherry picked @peterjc 's commits and added some more CMake stuff for enabling support on Windows.

**Comment by nehaljwani** [comment]
Resolved via: https://github.com/conda-forge/graphviz-feedstock/commit/9bbf22976dcddb93fbe452a7663f252e9ea09e3a, https://github.com/conda-forge/graphviz-feedstock/commit/5c51a0ada71968e6c8a24e11d2dceb3af3e89502, https://github.com/conda-forge/graphviz-feedstock/commit/8b2f95dba037bc3232de214d796750fc0da7cb20 and https://github.com/conda-forge/graphviz-feedstock/commit/e920ba7b1ab4e1cc05923bd53e2407d93f1e47bd

**Comment by jakirkham** [comment]
Great thank you Nehal! 😀

**Comment by peterjc** [comment]
Thanks all - happy to have helped in a small capacity.

**Pull request closed without merging**
