### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Fix #42 

Mainly rebuilding with conda-smithy so that newer versions of the dependencies are found. When trying to build locally, I needed to add several packages.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/graphviz,
I am not sure why the PPC build fails. It would be great if you could investigate this further and push a new version.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge/graphviz can this be merged, please? Currently graphviz relies on outdated dependencies which stops other packages to be installed as there are conflicts. I'm not sure what's wrong with the PPC build, but it shouldn't stop the other platforms to be broken.

**Comment by ocefpaf** [comment]
@Tobias-Fischer please consider adding yourself as a maintainer here ;-p

**Pull request merged**
