### PR TITLE
Quote paths in post-link script

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by nehaljwani** [comment]
Nice catch!

**Comment by peternowee** [comment]
@nehaljwani @jakirkham Oh, that reminds me, should something similar not also be done for `bld.bat`? See https://github.com/conda-forge/graphviz-feedstock/issues/43#issuecomment-627345228.

**Comment by jakirkham** [comment]
Usually Windows batch does not need this kind of thing unlike with UNIX bash.

**Comment by peternowee** [comment]
There were several reports from people where the batch file could not find the `.exe` because of a space in the path:

`'C:\Users\Ruslan' is not recognized as an internal or external command, operable program or batch file.`

And from https://github.com/pydot/pydot/issues/207:

`'D:\Program' 不是内部或外部命令，也不是可运行的程序或批处理文件。` (which means the same as above.)

And the responses below https://github.com/conda-forge/graphviz-feedstock/issues/43#issuecomment-627345228 indicate that the suggested solution worked.

**Comment by jakirkham** [comment]
Sure if you’d like to send a PR, that would be welcome. Certainly no harm in adding the quotes 🙂

**Comment by peternowee** [comment]
Not very happy about this, but alright then: conda-forge/graphviz-feedstock#64.

**Comment by jakirkham** [comment]
No worries. Thanks for doing that 😄

**Pull request merged**
