### PR TITLE
Compile with librsvg

### PR DESCRIPTION
**Pull request by jakobandersen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempt at fixing #53.

### CODE REVIEW

**Comment by jakobandersen** [comment]
@conda-forge-admin, please rerender

**Comment by jakobandersen** [comment]
I'm not sure why it fails on macOS. The compilation error seems unrelated to the change.
I probably should have checked before submitting this PR, but #48 seems to be the exact same change, except for just Linux.

**Comment by ocefpaf** [comment]
I'm not a mac expert not I have one to test, sorry. Maybe you can ask in [our community gitter channel for help](https://gitter.im/conda-forge/conda-forge.github.io).

**Comment by jakobandersen** [comment]
> I'm not a mac expert not I have one to test, sorry. Maybe you can ask in [our community gitter channel for help](https://gitter.im/conda-forge/conda-forge.github.io).

Thanks, and sorry for the open/close spamming. I was hoping the macOS issue was intermittent but it indeed seems to persist.

**Comment by ocefpaf** [comment]
> Thanks, and sorry for the open/close spamming. I was hoping the macOS issue was intermittent but it indeed seems to persist.

Don't worry. I do that a lot :smile:

**Comment by mariusvniekerk** [comment]
Might be worthwhile just doing this one for linux?

**Comment by jakobandersen** [comment]
@mariusvniekerk, yes, that would be good. Basically that's what #48 does, so if than one is merged I'll just update the build number here accordingly.

**Comment by jakobandersen** [comment]
(Fixed via #59 instead)

**Pull request closed without merging**
