### PR TITLE
Bump version to 2.46.1 & add support for Windows

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

```
- Add support for Windows using CMake
- Add support for rsvg and gd
- Replace use of uname with target_platform
- Consolidate all test commands in run_tests script
- Switch to gitlab source release instead of sdist (link no longer
  updated)
- Drop needless dependency on libpng/libtiff/libjpeg (graphviz uses
  pango/cairo to deal with these formats instead of using them directly)
```

Also resolves https://github.com/conda-forge/graphviz-feedstock/issues/53

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin Restart CI

**Comment by nehaljwani** [comment]
@conda-forge/graphviz This is ready for review!

**Comment by nehaljwani** [comment]
@conda-forge-admin Please re-render!

**Comment by ocefpaf** [comment]
You rock @nehaljwani!

**Comment by jakirkham** [comment]
Agreed. Thanks for all this work Nehal! 😀

**Comment by jsignell** [comment]
Reposting from #55. We are running into some issues in the dask test suite on windows. Seems like it is probably related to this change. https://github.com/dask/dask/issues/7231

**Comment by jakirkham** [comment]
I think we need to drop the patch from the `python-graphviz` package. Would someone be able to submit a PR?

**Comment by ccordoba12** [comment]
@jsignell, it seems you're calling directly `dot.bat` in your tests. You should call `dot` (or `dot.exe`) instead now.

**Comment by jsignell** [comment]
> seems you're calling directly dot.bat in your tests. 

I think I just copied the wrong bit of the stack trace. The dask bit is: 

```
2021-02-16T16:19:08.0682898Z dask\tests\test_base.py:929: 
2021-02-16T16:19:08.0683787Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2021-02-16T16:19:08.0684211Z dask\base.py:213: in visualize
2021-02-16T16:19:08.0684644Z     **kwargs,
2021-02-16T16:19:08.0685041Z dask\base.py:670: in visualize
2021-02-16T16:19:08.0685850Z     return dot_graph(dsk, filename=filename, **kwargs)
2021-02-16T16:19:08.0686548Z dask\dot.py:272: in dot_graph
2021-02-16T16:19:08.0687026Z     return graphviz_to_file(g, filename, format)
2021-02-16T16:19:08.0687574Z dask\dot.py:284: in graphviz_to_file
2021-02-16T16:19:08.0688016Z     data = g.pipe(format=format)
2021-02-16T16:19:08.0688750Z C:\Miniconda3\envs\test-environment\lib\site-packages\graphviz\files.py:171: in pipe
2021-02-16T16:19:08.0689387Z     quiet=quiet)
2021-02-16T16:19:08.0690086Z C:\Miniconda3\envs\test-environment\lib\site-packages\graphviz\backend.py:250: in pipe
2021-02-16T16:19:08.0691112Z     out, _ = run(cmd, input=data, capture_output=True, check=True, quiet=quiet)
2021-02-16T16:19:08.0692089Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```

**Comment by jsignell** [comment]
> I think we need to drop the patch from the `python-graphviz` package. Would someone be able to submit a PR?

I can open a PR to drop it.

**Comment by ccordoba12** [comment]
Yeah, sorry, the problem is on `python-graphviz`.

**Comment by jsignell** [comment]
I took a stab at the python-graphviz PR https://github.com/conda-forge/python-graphviz-feedstock/pull/44

**Comment by jakirkham** [comment]
Thank you! Also reviewed. Please let us know if you have any questions 🙂

**Pull request merged**
