### PR TITLE
update to graphviz 2.42.3 and update source code urls

### PR DESCRIPTION
**Pull request by FelixHoehleQC**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FelixHoehleQC** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge/core, I don't understand why we're not able to rerender this.

**Comment by mbargull** [comment]
IIRC, "it looks like there was nothing to do" just means "everything up to date; rerendering did not change anything". So you should be good to go.

**Comment by mbargull** [comment]
Yep, the last rerender was pretty recent: https://github.com/fhoehle/graphviz-feedstock/commit/c9c2464ffa45dcd2ddb7118a68ca4cadf5f2b3b2
There haven't been signification changes to `conda-{build,smithy,forge-pinning}` since then, I believe.

**Comment by isuruf** [comment]
Please send some suggestions on wording at https://github.com/conda-forge/conda-forge-webservices/blob/7af2eb6d87b1c5cf806d9bdd862267fdf2dfeaa3/conda_forge_webservices/commands.py#L139

**Comment by FelixHoehleQC** [comment]
> @conda-forge/core, I don't understand why we're not able to rerender this.

@ccordoba12 `master` was rendered 7 days ago, only `conda-forge-pinning` has changed: 
2019.11.18 -> 2019.11.20. So no significant changes were found.

**Comment by xhochy** [comment]
@conda-forge/graphviz This is looking good, can you review/merge?

**Pull request merged**
