### PR TITLE
Add fonts-conda-ecosystem to requirements

### PR DESCRIPTION
**Pull request by mvdbeek**
Otherwise svg files don't render in minimal environments.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Could anyone please take a look at this ?

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by mvdbeek** [comment]
`Format: "png" not recognized. Use one of:` Looks like a dependency might be missing here ?

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
