### PR TITLE
Added the dependency librsvg to enable svg to pdf conversion plugin.

### PR DESCRIPTION
**Pull request by Nojgaard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Nojgaard** [comment]
I'm sorry, not entirely sure why this build would be cancelled. Do you have any suggestions of what I'm missing?

**Comment by Nojgaard** [comment]
In Travi CI, I also get: `Format: "png" not recognized. Use one of:`

Does anyone know why this is?

**Comment by Nojgaard** [comment]
@conda-forge-admin, please rerender

**Comment by Nojgaard** [comment]
Hey!

Is there any chance this will be merged, or does the librsvg dependency fall out of the scope of the project?

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Thanks for the work! This got handed recently with PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 ). Please give that a try and let us know how it goes 🙂

**Pull request closed without merging**
