### PR TITLE
Reenable windows build

### LINKED ISSUE #55: Updated versions
@jjhelmus, @jakirkham I am a core developer of NetworkX and pygraphviz.  We keep getting bug reports from users trying to install pygraphviz with conda.  It looks like you've stopped providing recent versions for Windows and your Mac build is failing.

Is there anything I can do to help?

### PR DESCRIPTION
**Pull request by jarrodmillman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) **I updated the build number in recipe/meta.yaml, not sure if that is the right number to incrememnt**
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #55.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
If you have a Windows machine to test on, can also try building locally to debug/iterate faster. Would just run the following from the feedstock root directory.

```
conda build -m .ci_support\win_64_.yaml recipe
```

The relevant build steps are in `recipe/bld.bat`, which is just a Windows batch file. Anything that is valid in batch is valid there.

**Comment by jarrodmillman** [comment]
I haven't been on a Windows machine since around 1993 and I've never used conda.

**Comment by jarrodmillman** [comment]
It looks like it is failing on OS X and Windows.  Do you also need me to sort out the OS X issues?  I don't use OS X either.

**Comment by jarrodmillman** [comment]
It looks like it is trying to build graphviz-2.42.3.
```
BUILD START: ['graphviz-2.42.3-h0e60522_3.tar.bz2']
```
I thought we were trying to get it to use graphviz-install-2.44.1-win64.exe from https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/

Should I set ``{% set version = "2.42.3" %}`` to  ``{% set version = "2.44.1" %}`` in ``main.yaml``?  Where do I specify where it is supposed to download the binary from?  Should I add a line like
```
  url: https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/graphviz-{{ version }}-win64.exe  # [win]
  md5: <whatever it is>  # [win]
```
to ``main.yaml``?

Do I need to modify ``bld.bat``?  I am not sure why a compiler is even needed, if we are trying to use a prebuilt binary.

I also noticed the following warning
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
```

I am not sure why it is looking for numpy.  I also can't figure out where it is downloading the prebuilt graphviz binary.

**Pull request closed without merging**
